翻譯一小部分
MagicTeaMC/pterodactyl-tw pull request #5
Opened 2024-02-09 07:53 UTC by RyanisyydsTT

2024-02-09 08:51 UTC, MagicTeaMC requested changes

2024-02-09 08:51 UTC, MagicTeaMC commented on resources/views/admin/index.blade.php
> +    <h1>管理總覽<small>快速瀏覽您的主機.</small></h1>
system=系統

2024-02-09 08:51 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
> +                                    <p class="text-muted small">如果啟用，登入表單和密碼重設表單將進行無聲驗證並在需要時顯示可見驗證。</p>
翻譯錯誤

2024-02-09 08:51 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
> +                                        您當前使用的是與此面板一起發送的 reCAPTCHA 金鑰。為了提高安全性，建議 <a href="https://www.google.com/recaptcha/admin">生成新的隱形 reCAPTCHA 金鑰</a>，專門綁定到您的網站。
翻譯錯誤

2024-02-09 09:04 UTC, RyanisyydsTT commented
Fixed!

2024-02-09 09:56 UTC, RyanisyydsTT commented
~~試試看Discord Ping可不可以在GitHub 運行w~~<@1170720196688871444>

2024-02-10 03:18 UTC, MagicTeaMC requested changes

2024-02-10 03:18 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
> +    <h1>進階設定<small>為 Pterodactyl 配置進階設定。</small></h1>
「設定」
「配置」是中國用語

2024-02-10 03:18 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
> +                        <h3 class="box-title">HTTP 連接</h3>
connection 在這邊翻譯成「連線」比較合適

2024-02-10 03:18 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
>                                  <div>
same

2024-02-10 03:18 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
> +                        <h3 class="box-title">自動分配創建</h3>
pterodactyl 中的 allocation 其實是指主機的埠(port)

2024-02-10 03:18 UTC, MagicTeaMC commented on resources/views/admin/settings/advanced.blade.php
> +                                <label class="control-label">起始端口</label>
「埠」
「端口」是中國用語

2024-02-10 04:28 UTC, RyanisyydsTT commented
Done

2024-02-22 15:08 UTC, MagicTeaMC commented
Any new updates?

2024-02-22 15:15 UTC, Ryanisyyds commented
Maybe at Saturday or Sunday
好耶作業好多

2024-02-22 15:34 UTC, MagicTeaMC commented
Well...okay

2024-03-20 11:31 UTC, RyanisyydsTT commented
# Done List
- resourses/views/admin/api
- resourses/views/admin/databases
- resourses/views/admin/location
- resourses/views/admin/nests
- resourses/views/admin/settings
- resourses/views/admin/users
- resourses/views/admin/index.blade.php

# Unfinished List
- resourses/views/admin/eggs
- resourses/views/admin/mounts
- resourses/views/admin/nodes

2024-03-20 11:39 UTC, MagicTeaMC commented
tested? or translated

2024-03-20 12:35 UTC, RyanisyydsTT commented
Translated

2024-05-11 01:24 UTC, MagicTeaMC commented
maybe time to merge it?

2024-05-11 02:43 UTC, RyanisyydsTT commented
Merge first, got no free time .w.

2024-08-22 14:28 UTC, merged